# Generated by Django 5.2.1 on 2025-05-28 04:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_login', '用户登录'), ('user_logout', '用户登出'), ('user_register', '用户注册'), ('user_update', '用户信息更新'), ('user_delete', '用户删除'), ('user_password_change', '用户密码修改'), ('user_password_reset', '用户密码重置'), ('project_create', '项目创建'), ('project_update', '项目更新'), ('project_delete', '项目删除'), ('device_create', '设备创建'), ('device_update', '设备更新'), ('device_delete', '设备删除'), ('device_online', '设备上线'), ('device_offline', '设备离线'), ('sensor_create', '传感器创建'), ('sensor_update', '传感器更新'), ('sensor_delete', '传感器删除'), ('actuator_create', '执行器创建'), ('actuator_update', '执行器更新'), ('actuator_delete', '执行器删除'), ('actuator_command', '执行器命令发送'), ('strategy_create', '策略创建'), ('strategy_update', '策略更新'), ('strategy_delete', '策略删除'), ('strategy_enable', '策略启用'), ('strategy_disable', '策略禁用'), ('strategy_execution', '策略执行'), ('invitation_create', '邀请码创建'), ('invitation_use', '邀请码使用'), ('system_startup', '系统启动'), ('system_shutdown', '系统关闭'), ('system_config_change', '系统配置变更')], db_index=True, max_length=100, verbose_name='操作类型')),
                ('target_object_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='目标对象ID')),
                ('target_object_repr', models.CharField(blank=True, max_length=255, null=True, verbose_name='目标对象描述')),
                ('details', models.JSONField(blank=True, default=dict, null=True, verbose_name='详细信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间戳')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='目标对象类型')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
