# Generated by Django 5.2.1 on 2025-05-28 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='项目ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='设备ID')),
                ('device_identifier', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备物理标识')),
                ('device_key', models.CharField(editable=False, max_length=128, verbose_name='设备密钥')),
                ('name', models.CharField(max_length=200, verbose_name='设备名称')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unregistered', '未注册'), ('error', '错误'), ('disabled', '已禁用')], default='unregistered', max_length=20, verbose_name='状态')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='最后在线时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='iot_devices.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='传感器名称')),
                ('sensor_type', models.CharField(max_length=50, verbose_name='传感器类型')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('value_key', models.CharField(max_length=100, verbose_name='数据键名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='iot_devices.device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '传感器',
                'verbose_name_plural': '传感器',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Actuator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='执行器名称')),
                ('actuator_type', models.CharField(max_length=50, verbose_name='执行器类型')),
                ('command_key', models.CharField(max_length=100, verbose_name='命令键名')),
                ('current_state_payload', models.JSONField(blank=True, default=dict, null=True, verbose_name='当前状态数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuators', to='iot_devices.device', verbose_name='所属设备')),
            ],
            options={
                'verbose_name': '执行器',
                'verbose_name_plural': '执行器',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('device', 'command_key'), name='unique_command_key_per_device'), models.UniqueConstraint(fields=('device', 'name'), name='unique_actuator_name_per_device')],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('device_identifier__isnull', False)), fields=('project', 'device_identifier'), name='unique_device_identifier_per_project'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('device', 'value_key'), name='unique_value_key_per_device'),
        ),
        migrations.AddConstraint(
            model_name='sensor',
            constraint=models.UniqueConstraint(fields=('device', 'name'), name='unique_sensor_name_per_device'),
        ),
    ]
