# Generated by Django 5.2.1 on 2025-05-28 03:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorCommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_payload', models.JSONField(default=dict, verbose_name='命令内容')),
                ('status', models.CharField(choices=[('pending_send', '待发送'), ('sent', '已发送'), ('acknowledged', '已确认'), ('failed', '执行失败'), ('timeout', '执行超时')], default='pending_send', max_length=30, verbose_name='状态')),
                ('source', models.CharField(blank=True, choices=[('user_ui', '用户界面'), ('api_call', 'API调用'), ('strategy_engine', '策略引擎')], max_length=30, null=True, verbose_name='来源')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('response_payload', models.JSONField(blank=True, default=dict, null=True, verbose_name='响应内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='iot_devices.actuator', verbose_name='执行器')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actuator_commands', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '执行器命令日志',
                'verbose_name_plural': '执行器命令日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='时间戳')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='浮点值')),
                ('value_string', models.CharField(blank=True, max_length=255, null=True, verbose_name='字符串值')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='布尔值')),
                ('value_json', models.JSONField(blank=True, default=dict, null=True, verbose_name='JSON值')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_records', to='iot_devices.sensor', verbose_name='传感器')),
            ],
            options={
                'verbose_name': '传感器数据',
                'verbose_name_plural': '传感器数据',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['sensor', '-timestamp'], name='iot_devices_sensor__d4a020_idx')],
            },
        ),
    ]
