# Generated by Django 5.2.1 on 2025-05-30 09:55

import iot_devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0002_actuatorcommandlog_sensordata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(default=iot_devices.models.generate_device_id, editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_key',
            field=models.CharField(editable=False, max_length=50, verbose_name='设备密钥'),
        ),
    ]
